### ISSUE TITLE
Loss landscape visualization code

### ISSUE THREAD

**Issue by hossein1387** [HuangOwen/VVTQ#2]
I am not able to find how you produced Figure 6. I am aware of [Visualizing the Loss Landscape of Neural Nets](https://github.com/tomgoldstein/loss-landscape) and it seems Figure 6 was produced by that code. Could you please confirm?

**Comment by HuangOwen** [comment]
Sure, I can confirm that Figure 6 is produced by https://github.com/tomgoldstein/loss-landscape
